siteName = "Arman lost in (multidimensional) space"
theme = "HR_Publisher"
disqusShortname = ""
BuilPath = "/path-to-hrocket-directory/hrocket/docs"
publishDir = ""
logoLink = "/"

[params]
    description = ""
    [params.logo]
      url = "logo.png"
      width = 50
      height = 50
      alt = "Logo"
    [params.favIcon]
      url = "favicon.ico"

