siteName = "Arman lost in (multidimensional) space"
theme = "HR_Publisher"
disqusShortname = ""
BuilPath = "/home/your-username/hrocket/docs"
publishDir = ""
logoLink = "/"
metaKeywords = "HTML, CSS, XML, XHTML, JavaScript"
googleAnalyticsTrackingId = "UA-232232-34"
siteUrl = "http://example.com"

[params]
    description = ""
    [params.logo]
      url = "logo.png"
      width = 50
      height = 50
      alt = "Logo"
    [params.favIcon]
      url = "favicon.ico"

